id: I5A6567EA
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:07:38.536046
last_modified: 2023-02-08 15:07:38.536162
source_metadata:
  title: 'RK: Gaṅgottaraparipṛcchā'
  language: en
bases:
  '6531':
    base_file: 6531.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
